export const FETCH_COCKTAIL = 'FETCH_COCKTAIL';
export const FETCH_COCKTAILS = 'FETCH_COCKTAILS';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const MATCH_INGREDIENTS = 'MATCH_INGREDIENTS';