export const FETCH_COCKTAIL = 'FETCH_COCKTAIL';
export const FETCH_COCKTAILS = 'FETCH_COCKTAILS';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_SAVED_COCKTAIL = 'FETCH_SAVED_COCKTAILS';
export const FETCH_SAVED_COCKTAILS = 'FETCH_SAVED_COCKTAILS';
export const FETCH_USER = 'FETCH_USER';
export const MATCH_INGREDIENTS = 'MATCH_INGREDIENTS';